# src/models/response.py

from typing import Any, Dict

from pydantic import BaseModel, Field


class ExplainResponse(BaseModel):
    """
    统一返回结构：
    - explanation: 给前端 / 用户看的自然语言解释
    - fde_raw: 结构化的原始 FDE 结果（方便前端画图）
    """

    explanation: str = Field(
        ...,
        description="Human-readable explanation generated by the LLM.",
    )
    fde_raw: Dict[str, Any] = Field(
        ...,
        description="Raw numeric results from FDEEngine for visualization.",
    )
